spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL10Dialect
  show-sql: true
  format-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: INFO
